In [1]:
#Install all the Reqiuired Libraries and Packages 
import os
import glob
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile
from python_speech_features import mfcc , logfbank
import librosa as lr
import os, glob, pickle
import librosa
from scipy import signal
import noisereduce as nr
from glob import glob
import librosa
get_ipython().magic('matplotlib inline')

G:\ANACONDA3\lib\site-packages\tqdm\autonotebook\__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)


In [2]:
#Loading the required RAVDESS DataSet with length of 1439 Audio Files 
os.listdir(path='.\speech-emotion-recognition-ravdess-data')
def getListOfFiles(dirName):
    listOfFile=os.listdir(dirName)
    allFiles=list()
    for entry in listOfFile:
        fullPath=os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles=allFiles + getListOfFiles(fullPath)
        else:
            allFiles.append(fullPath)
    return allFiles

dirName = './speech-emotion-recognition-ravdess-data'
listOfFiles = getListOfFiles(dirName)
len(listOfFiles)

60

In [3]:
#Use the Speech-Recognition API to get the Raw Text from Audio Files, Though Speech Recognition
#is less strong for large chunk of files , so used Error Handling , where when it is not be able to 
#produce the text of a particular Audio File it prints the statement 'error'.Just for understanding Audio
import speech_recognition as sr
r=sr.Recognizer()
for file in range(0 , len(listOfFiles) , 1):
    with sr.AudioFile(listOfFiles[file]) as source:
        audio = r.listen(source)
        try:
            text = r.recognize_google(audio)
            print(text)
        except:
            print('error')

talking by the door
kids talking by the door
dog sitting by the door
talk to Siri why the door
error
talking by the door
the door
dog sitting by the door
change your talking by the door
talking by the door
dog sitting by the door
sitting by the door
talking by the door
talking by the door
dog sitting by the door
dogs are sitting by the door
talking by the door
error
sitting by the door
dogs are sitting by the door
kids talking by the door
khesa talking by the door
sitting by the door
error
kids talking by the door
talking by the door
dogs are sitting by the door
sitting by the door
kids are talking by the door
talking by the door
sitting by the door
sitting by the door
talking by the door
talking by the door
dogs are sitting by the door
spelling for the tour
talking by the door
kids talking by the door
toxicity by the door
dogs sitting by the door
f****** by the door
talking to the door
Rockstar ceiling by the door
ceiling
the door
error
sitting by the door
error
kids talking by the do

In [ ]:
#Plotting the Basic Graphs for understanding of Audio Files :
for file in range(0 , len(listOfFiles) , 1):
    audio , sfreq = lr.load(listOfFiles[file])
    time = np.arange(0 , len(audio)) / sfreq
    
    fig ,ax = plt.subplots()
    ax.plot(time , audio)
    ax.set(xlabel = 'Time (s)' , ylabel = 'Sound Amplitude')
    plt.show()
    
#PLOT THE SEPCTOGRAM
for file in range(0 , len(listOfFiles) , 1):
    samples,sample_rate =librosa.load(listOfFiles[file])#      sample_rate , samples = wavfile.read(listOfFiles[file])
    frequencies , times, spectrogram = signal.spectrogram(samples, sample_rate) 
    plt.pcolormesh(times, frequencies, spectrogram)
    plt.imshow(spectrogram)
    plt.ylabel('Frequency [Hz]')
    plt.xlabel('Time [sec]')
plt.show()

In [ ]:
#Next Step is In-Depth Visualisation of Audio Fiels and its certain features to plot for.
#They are the Plotting Functions to be called later. 
def plot_signals(signals):
    fig , axes = plt.subplots(nrows=2, ncols=5,sharex =False , sharey=True, figsize=(20,5))
    fig.suptitle('Time Series' , size=16)
    i=0
    for x in range(2):
        for y in range(5):
            axes[x,y].set_title(list(signals.keys())[i])
            axes[x,y].plot(list(signals.values())[i])
            axes[x,y].get_xaxis().set_visible(False)
            axes[x,y].get_yaxis().set_visible(False)
            i +=1

def plot_fft(fft):
    fig , axes = plt.subplots(nrows=2, ncols=5,sharex =False , sharey=True, figsize=(20,5))
    fig.suptitle('Fourier Transform' , size=16)
    i=0
    for x in range(2):
        for y in range(5):
            data = list(fft.values())[i]
            Y,freq = data[0] , data[1]
            axes[x,y].set_title(list(fft.keys())[i])
            axes[x,y].plot(freq , Y)
            axes[x,y].get_xaxis().set_visible(False)
            axes[x,y].get_yaxis().set_visible(False)
            i +=1
    
def plot_fbank(fbank):
    fig , axes = plt.subplots(nrows=2, ncols=5,sharex =False , sharey=True, figsize=(20,5))
    fig.suptitle('Filter Bank Coefficients' , size=16)
    i=0
    for x in range(2):
        for y in range(5):
            axes[x,y].set_title(list(fbank.keys())[i])
            axes[x,y].imshow(list(fbank.values())[i],cmap='hot', interpolation = 'nearest')
            axes[x,y].get_xaxis().set_visible(False)
            axes[x,y].get_yaxis().set_visible(False)
            i +=1
            
def plot_mfccs(mfccs):
    fig , axes = plt.subplots(nrows=2, ncols=5,sharex =False , sharey=True, figsize=(20,5))
    fig.suptitle('Mel Frequency Capstrum  Coefficients' , size=16)
    i=0
    for x in range(2):
        for y in range(5):
            axes[x,y].set_title(list(mfccs.keys())[i])
            axes[x,y].imshow(list(mfccs.values())[i],
                             cmap='hot', interpolation = 'nearest')
            axes[x,y].get_xaxis().set_visible(False)
            axes[x,y].get_yaxis().set_visible(False)
            i +=1

def calc_fft(y,rate):
    n = len(y)
    freq = np.fft.rfftfreq(n , d= 1/rate)
    Y= abs(np.fft.rfft(y)/n)
    return(Y,freq)

In [ ]:
# Here The Data Set is loaded and plots are Visualised by Calling the Plotting Functions . 
import matplotlib.pyplot as plt
from scipy.io import wavfile as wav
from scipy.fftpack import fft
import numpy as np
for file in range(0 , len(listOfFiles) , 1):
    data,rate =librosa.load(listOfFiles[file])      #     rate, data = wav.read(listOfFiles[file])   
    fft_out = fft(data)
    %matplotlib inline
    plt.plot(data, np.abs(fft_out))
    plt.show()
    
signals={}
fft={}
fbank={}
mfccs={}
# load data
for file in range(0 , len(listOfFiles) , 1):
#     rate, data = wavfile.read(listOfFiles[file])
     signal,rate =librosa.load(listOfFiles[file] , sr=44100)
     mask = envelope(signal , rate , 0.0005)
     signals[file] = signal
     fft[file] = calc_fft(signal , rate)
    
     bank = logfbank(signal[:rate] , rate , nfilt = 26, nfft = 1103).T
     fbank[file] = bank
     mel = mfcc(signal[:rate] , rate , numcep =13 , nfilt = 26 , nfft=1103).T
     mfccs[file]=mel

plot_signals(signals)
plt.show()

plot_fft(fft)
plt.show()

plot_fbank(fbank)
plt.show()

plot_mfccs(mfccs)
plt.show()

In [9]:
#Now Cleaning Step is Performed where:
#DOWN SAMPLING OF AUDIO FILES IS DONE  AND PUT MASK OVER IT AND DIRECT INTO CLEAN FOLDER
#MASK IS TO REMOVE UNNECESSARY EMPTY VOIVES AROUND THE MAIN AUDIO VOICE 
def envelope(y , rate, threshold):
    mask=[]
    y=pd.Series(y).apply(np.abs)
    y_mean = y.rolling(window=int(rate/10) ,  min_periods=1 , center = True).mean()
    for mean in y_mean:
        if mean>threshold:
            mask.append(True)
        else:
            mask.append(False)
    return mask

In [10]:
#The clean Audio Files are redirected to Clean Audio Folder Directory 
import glob,pickle
# for file in tqdm(glob.glob(r'C:\Users\Sakshi jain\speech-emotion-recognition-ravdess-data\\**\\*.wav')):
for file in tqdm(glob.glob(r'C:\Users\PRIYANSHU PANDEY\Desktop\Stuti\Ravdess small sample datase\speech-emotion-recognition-ravdess-data\\**\\*.wav')):
    file_name = os.path.basename(file)
    signal , rate = librosa.load(file, sr=16000)
    mask = envelope(signal,rate, 0.0005)
    wavfile.write(filename= r'C:\Users\PRIYANSHU PANDEY\Desktop\Stuti\Ravdess small sample datase\clean_speech\\'+str(file_name), rate=rate,data=signal[mask])

100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:11<00:00,  5.06it/s]


In [11]:
#All the Required Packages and Libraies are installed.
import soundfile
from tensorflow.keras.layers import Conv2D,MaxPool2D, Flatten, LSTM
from keras.layers import Dropout,Dense,TimeDistributed
from keras.models import Sequential
from keras.utils import to_categorical 
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

Using TensorFlow backend.


In [12]:
#Feature Extraction of Audio Files Function 
#Extract features (mfcc, chroma, mel) from a sound file
def extract_feature(file_name, mfcc, chroma, mel):
    with soundfile.SoundFile(file_name) as sound_file:
        X = sound_file.read(dtype="float32")
        sample_rate=sound_file.samplerate
        if chroma:
            stft=np.abs(librosa.stft(X))
        result=np.array([])
        if mfcc:
            mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T, axis=0)
        result=np.hstack((result, mfccs))
        if chroma:
            chroma=np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
        result=np.hstack((result, chroma))
        if mel:
            mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
        result=np.hstack((result, mel))
    return result

In [13]:
#Emotions in the RAVDESS dataset to be classified Audio Files based on . 
emotions={
  '01':'neutral',
  '02':'calm',
  '03':'happy',
  '04':'sad',
  '05':'angry',
  '06':'fearful',
  '07':'disgust',
  '08':'surprised'
}
#These are the emotions User wants to observe more :
observed_emotions=['calm', 'happy', 'fearful', 'disgust']

In [42]:
#Load the data and extract features for each sound file
from glob import glob
import os
import glob
def load_data(test_size=0.33):
    x,y=[],[]
    answer = 0
    for file in glob.glob(r'C:\Users\PRIYANSHU PANDEY\Desktop\Stuti\Ravdess small sample datase\clean_speech\\*.wav'):
        file_name=os.path.basename(file)
        emotion=emotions[file_name.split("-")[2]]
        if emotion not in observed_emotions:
            answer += 1
            continue
        feature=extract_feature(file, mfcc=True, chroma=True, mel=True)
        x.append(feature)
        y.append([emotion,file_name])
    return train_test_split(np.array(x), y, test_size=test_size, random_state=9)


In [64]:
#Split the dataset
import librosa
import numpy as np
x_train,x_test,y_trai,y_tes=load_data(test_size=0.25)
print(np.shape(x_train),np.shape(x_test), np.shape(y_trai),np.shape(y_tes))


(24, 180) (8, 180) (24, 2) (8, 2)


In [65]:
y_test_map = np.array(y_tes).T
y_test = y_test_map[0]
test_filename = y_test_map[1]
y_train_map = np.array(y_trai).T
y_train = y_train_map[0]
train_filename = y_train_map[1]
print(np.shape(y_train),np.shape(y_test))
print(*test_filename,sep="\n")

(24,) (8,)
03-01-02-02-01-01-01.wav
03-01-06-01-02-02-01.wav
03-01-03-01-01-02-01.wav
03-01-03-02-01-02-01.wav
03-01-03-01-02-02-01.wav
03-01-02-02-01-02-01.wav
03-01-02-02-02-02-01.wav
03-01-02-01-02-02-01.wav


In [66]:
#Get the shape of the training and testing datasets
# print((x_train.shape[0], x_test.shape[0]))
print((x_train[0], x_test[0]))

(array([-3.94841520e+02,  9.09605164e+01, -1.03667925e+01,  2.83785660e+01,
       -5.13291034e+00, -7.90893363e+00, -1.60141624e+01, -2.62665932e+01,
       -1.34115166e+01, -5.29609762e+00, -8.57799124e+00,  6.22029416e+00,
       -1.89102808e+01,  7.52303020e+00, -6.88778960e+00, -9.86481646e+00,
       -5.35330493e+00, -2.00894497e+00, -1.37563728e+01, -4.42616426e-01,
       -8.71958602e+00, -7.72621132e+00, -2.85401424e+00, -4.49695138e+00,
       -5.69129541e+00, -2.46792334e+00, -8.91658330e+00,  6.28479994e-01,
       -8.33700524e+00, -2.08200559e+00, -6.63993147e+00, -4.90928375e+00,
       -4.59367178e+00,  1.28458843e+00, -4.43022508e+00,  2.37076289e+00,
       -1.79906297e+00,  4.94486915e+00,  2.42389144e+00,  2.63770450e+00,
        6.24972950e-01,  6.62534216e-01,  5.90074892e-01,  5.88488630e-01,
        6.10359921e-01,  6.03769624e-01,  4.90683505e-01,  5.13769120e-01,
        5.39709270e-01,  5.30631902e-01,  5.20037695e-01,  5.27765536e-01,
        8.16207094e-04, 

In [36]:
#Get the number of features extracted
# print(f'Features extracted: {x_train.shape[1]}')

In [67]:
# Initialize the Multi Layer Perceptron Classifier
model=MLPClassifier(alpha=0.01, batch_size=256, epsilon=1e-08, hidden_layer_sizes=(300,), learning_rate='adaptive', max_iter=500)

In [68]:
#Train the model
model.fit(x_train,y_train)

G:\ANACONDA3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:351: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn("Got `batch_size` less than 1 or larger than "


MLPClassifier(activation='relu', alpha=0.01, batch_size=256, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(300,), learning_rate='adaptive',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [69]:
#Predict for the test set
print(x_test)
# y_pred=model.predict(x_test)
# y_pred.shape

[[-5.20614032e+02  1.17171435e+02  4.16630366e-01 ...  3.93839508e-06
   1.13687408e-06  5.87192719e-08]
 [-4.05837321e+02  8.57629892e+01 -1.27275260e+01 ...  1.82571301e-04
   4.11067921e-05  2.69036907e-06]
 [-4.23196873e+02  1.02849796e+02 -1.55268126e+01 ...  2.23983010e-05
   4.63932713e-06  2.28639453e-07]
 ...
 [-5.14689397e+02  1.06890684e+02 -2.00363480e+00 ...  1.59950670e-05
   2.75984489e-06  1.24071011e-07]
 [-4.85500973e+02  9.69459957e+01 -1.78040310e+00 ...  4.53421642e-05
   8.13862794e-06  3.69782932e-07]
 [-4.61759397e+02  1.17045060e+02 -9.08470311e+00 ...  3.65003157e-05
   4.64132073e-06  2.53890407e-07]]


In [70]:
#LAST Visualisation (Summarisation)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
results = confusion_matrix(y_test, y_pred) 
print('Confusion Matrix')
print(results) 
print ('Accuracy Score :',accuracy_score(y_test, y_pred) )
print('Report')
print (classification_report(y_test, y_pred))

Confusion Matrix
[[4 0 0]
 [0 1 0]
 [0 0 3]]
Accuracy Score : 1.0
Report
              precision    recall  f1-score   support

        calm       1.00      1.00      1.00         4
     fearful       1.00      1.00      1.00         1
       happy       1.00      1.00      1.00         3

   micro avg       1.00      1.00      1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [ ]:
#The problem is here . After Prediction I only get the predicted results where as i also want that predicted 
# output should match their label and corresponding filename for the particular prediction should
#also be printed in .csv file .

In [81]:
#Store the Prediction probabilities into CSV file 
import numpy as np
import pandas as pd
y_pred1 = pd.DataFrame(y_pred, columns=['predictions'])
y_pred1['file_names'] = test_filename
print(y_pred1)
y_pred1.to_csv('predictionfinal.csv') 

  predictions                file_names
0        calm  03-01-02-02-01-01-01.wav
1     fearful  03-01-06-01-02-02-01.wav
2       happy  03-01-03-01-01-02-01.wav
3       happy  03-01-03-02-01-02-01.wav
4       happy  03-01-03-01-02-02-01.wav
5        calm  03-01-02-02-01-02-01.wav
6        calm  03-01-02-02-02-02-01.wav
7        calm  03-01-02-01-02-02-01.wav


In [82]:
# For verification type
print(y_test_map.T)

[['calm' '03-01-02-02-01-01-01.wav']
 ['fearful' '03-01-06-01-02-02-01.wav']
 ['happy' '03-01-03-01-01-02-01.wav']
 ['happy' '03-01-03-02-01-02-01.wav']
 ['happy' '03-01-03-01-02-02-01.wav']
 ['calm' '03-01-02-02-01-02-01.wav']
 ['calm' '03-01-02-02-02-02-01.wav']
 ['calm' '03-01-02-01-02-02-01.wav']]
